# vim: noai:ts=2:sw=2:ft=yaml:
language: minimal

git:
  depth: 1

sudo: required

services:
  - docker

# setup dependencies required for testing
before_install:
  - docker pull fedora:32

# execute unit testing and code coverage
install:
  - docker run -uroot --network host -it --volume $PWD:/src/sg-bridge:z --workdir /src/sg-bridge fedora:32 /bin/sh -c 'sh ./build/build_checks.sh'
